# Generated by Django 5.0.2 on 2024-02-23 00:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ManyToManyField(related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
